/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.mimi.cineproyecto.ui;

/**
 *
 * @author Propietario
 */
import javax.swing.*;
import java.awt.*;
import java.util.List;
import mx.itson.mimi.cineproyecto.Boleto;
import mx.itson.mimi.cineproyecto.CineProyecto;

public class ReporteGeneralFrame extends JFrame {

    private JTextArea txtReporteGeneral;
    private JLabel lblTotales;
    private List<Boleto> listaBoletos;
    private CineProyecto cineProyecto; 

    public ReporteGeneralFrame(List<Boleto> listaBoletos, CineProyecto cineProyecto) {
        this.listaBoletos = listaBoletos;
        this.cineProyecto = cineProyecto;


        setTitle("Reporte General de Ventas");
        setSize(500, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());


        txtReporteGeneral = new JTextArea();
        txtReporteGeneral.setEditable(false);
        cargarReporte();

        JScrollPane scrollPane = new JScrollPane(txtReporteGeneral);


        lblTotales = new JLabel();
        actualizarTotales();


        JButton btnVolver = new JButton("Volver");
        btnVolver.addActionListener(e -> {
            new MainFrame(cineProyecto).setVisible(true);  
            dispose();  
        });

        JPanel panelInferior = new JPanel(new BorderLayout());
        panelInferior.add(lblTotales, BorderLayout.CENTER);
        panelInferior.add(btnVolver, BorderLayout.EAST);

        add(scrollPane, BorderLayout.CENTER);
        add(panelInferior, BorderLayout.SOUTH);

        setLocationRelativeTo(null);  // Tengo hambre
    }

    private void cargarReporte() {
        if (listaBoletos.isEmpty()) {
            txtReporteGeneral.setText("No hay boletos vendidos");
            return;
        }

        StringBuilder reporte = new StringBuilder();
        for (Boleto boleto : listaBoletos) {
            reporte.append(String.format("Cliente: %s | Película: %s | Asiento: %s | Precio: $%.2f\n",
                boleto.getCliente(), boleto.getPelicula(), boleto.getAsiento(), boleto.getPrecio()));
        }
        txtReporteGeneral.setText(reporte.toString());
    }

    private void actualizarTotales() {
        int totalBoletos = listaBoletos.size();
        double gananciaTotal = listaBoletos.stream().mapToDouble(Boleto::getPrecio).sum();
        lblTotales.setText(String.format("Total Boletos Vendidos: %d | Ganancia Total: $%.2f", totalBoletos, gananciaTotal));
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnvolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtreportegeneral = new javax.swing.JTextArea();
        lbltotales = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnvolver.setText("Volver");

        txtreportegeneral.setColumns(20);
        txtreportegeneral.setRows(5);
        txtreportegeneral.setText("test\n");
        jScrollPane2.setViewportView(txtreportegeneral);

        lbltotales.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnvolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(lbltotales))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lbltotales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(btnvolver))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteGeneralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteGeneralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteGeneralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteGeneralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnvolver;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbltotales;
    private javax.swing.JTextArea txtreportegeneral;
    // End of variables declaration//GEN-END:variables
}
